### ISSUE TITLE
Discussion of v1.8.x Roadmap

### ISSUE THREAD

**Issue by decentral1se** [Mailu/Mailu#1829]
As proposed in the last project meeting (https://github.com/Mailu/Mailu/issues/1582#issuecomment-862642385), we are experimenting with a discussion driven model for determining the roadmap of the next release. This follows the existing practice of the succesful community run project Gitea (e.g https://github.com/go-gitea/gitea/issues/14477).

Starting point for the roadmap is:

- [x] master version postgresql database roundcube webmail 502 Bad Gateway https://github.com/Mailu/Mailu/issues/1648
- [ ] HOST_* and *_ADDRESS resolution errors for docker-compose deployments https://github.com/Mailu/Mailu/issues/1341
- [x] https://travis-ci.org/ ceased. We need to switch to a new CI/CD pipeline https://github.com/Mailu/Mailu/issues/1828
 
These have been derived from the existing milestones: [1.8-rc](https://github.com/Mailu/Mailu/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.8-rc) and [1.8](https://github.com/Mailu/Mailu/milestone/11) and the discussion from the last meeting.

This release is 7 months overdue following the original milestone deadline (for `$reasons`) and it was discussed a little bit that we should try to minimise what we include in this roadmap so as to be able to make a release sooner rather than later. Please also bear in mind, the project has very little capacity right now and none of the new would-be maintainers have access to actually get things merged. We're on the way though.

@nextgens I am not sure which our your current PRs were suggested to also be up for inclusion in https://github.com/Mailu/Mailu/pulls/nextgens re: pressing issues with regard to security? Please let us know.

**Comment by nextgens** [comment]
I was talking about #1787 (already merged in master but the backport is blocked) that became #1791.

We should also consider updating the various webmails (#1739 and its successor).

We need a solution for #1612 ; My vote goes towards "documenting the problem" (explain the problem and a workaround: setting a stupidly high limit).

**Comment by Diman0** [comment]
1.8 (current rc) has indeed been waiting for 6 months to be released already. 1.7 (current stable) was released about 1.5 years ago. So people on stable (1.7) have been waiting for 1.5 years already for an update. I think we should focus on a 1.8 release within a couple of months.

I suggest to first address
- #1828
- #1791
- Update all involved libraries and components.

and release 1.8 as is. #1648 already has a workaround. #1739 has a workaround as mentioned by nextgens. We can document this.

Having a secure mailserver is one of the [core goals](https://mailu.io/master/general.html#philosophy) of the Mailu project. That is why I think that #1791 and updating all involved software/libraries (to address known CVE) is important for 1.8.  Anything else can be postponed for the release after that to reduce scope.

**Comment by parisni** [comment]
I am about to work on https://github.com/Mailu/Mailu/issues/1648 . That might be available for 1.8, let's see

**Comment by parisni** [comment]
I suggest we introduce github releases from 1.8 (see https://github.com/Mailu/Mailu/issues/1245). I haven't found in the documentation any release guide, but keeping the last github release to 1.5.1 on sept 2017 is not really a good signal from outside. I have some experience with release-it, and I can work on this.

**Comment by Diman0** [comment]
> I suggest we introduce github releases from 1.8 (see #1245). I haven't found in the documentation any release guide, but keeping the last github release to 1.5.1 on sept 2017 is not really a good signal from outside. I have some experience with release-it, and I can work on this.

For1.8rc there is already a [release](https://github.com/Mailu/Mailu/releases). I think it is not shown, because it is still marked as a pre-release.
All steps for doing a mailu release are documented here: https://github.com/Mailu/Mailu/wiki/Release-workflow
We documented these steps when we released 1.8rc.

**Comment by decentral1se** [comment]
> Having a secure mailserver is one of the core goals of the Mailu project. That is why I think that #1791 and updating all involved software/libraries (to address known CVE) is important for 1.8. Anything else can be postponed for the release after that to reduce scope.

FWIW I :100: agree with this.

Thanks for all the thoughts so far folks :partying_face: 

https://github.com/Mailu/Mailu/issues/1828 has already been closed off thanks to some heroic work!

**Comment by Erriez** [comment]
I'm curious: Is there a reason why https://mailu.io/ points to 1.7 and not 1.8?

**Comment by Diman0** [comment]
I'm closing this issue since 1.8 has been released.
